/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as ExperimentsIdRouteImport } from './routes/experiments.$id'
import { Route as ApiPublicExperimentIdRouteImport } from './routes/api/public/experiment.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIdRoute = ExperimentsIdRouteImport.update({
  id: '/experiments/$id',
  path: '/experiments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExperimentIdRoute = ApiPublicExperimentIdRouteImport.update({
  id: '/api/public/experiment/$id',
  path: '/api/public/experiment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/experiments/$id': typeof ExperimentsIdRoute
  '/api/public/experiment/$id': typeof ApiPublicExperimentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/experiments/$id': typeof ExperimentsIdRoute
  '/api/public/experiment/$id': typeof ApiPublicExperimentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/experiments/$id': typeof ExperimentsIdRoute
  '/api/public/experiment/$id': typeof ApiPublicExperimentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manage' | '/experiments/$id' | '/api/public/experiment/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manage' | '/experiments/$id' | '/api/public/experiment/$id'
  id:
    | '__root__'
    | '/'
    | '/manage'
    | '/experiments/$id'
    | '/api/public/experiment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRoute: typeof ManageRoute
  ExperimentsIdRoute: typeof ExperimentsIdRoute
  ApiPublicExperimentIdRoute: typeof ApiPublicExperimentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$id': {
      id: '/experiments/$id'
      path: '/experiments/$id'
      fullPath: '/experiments/$id'
      preLoaderRoute: typeof ExperimentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/experiment/$id': {
      id: '/api/public/experiment/$id'
      path: '/api/public/experiment/$id'
      fullPath: '/api/public/experiment/$id'
      preLoaderRoute: typeof ApiPublicExperimentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRoute: ManageRoute,
  ExperimentsIdRoute: ExperimentsIdRoute,
  ApiPublicExperimentIdRoute: ApiPublicExperimentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
